In [1]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.



In [2]:
type(array_list)

numpy.ndarray

In [3]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
for i in list_:
    print(type(i))

for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
array_list = np.array(list_, dtype = int)

Q3. Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [6]:
array_list.dtype

dtype('int64')

In [7]:
for i in list_:
    print(type(i))

for j in array_list:
    print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [8]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
num_array.size

6

In [10]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [11]:
arr = np.zeros((3,3))

In [12]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.fromfunction(lambda i,j:i*0,(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])